### PR TITLE
Update CMAQ_UG_tutorial_WRF-CMAQ_build_gcc.md

### PR DESCRIPTION
**Pull request by kmfoley**
This is just an initial PR to get David's edits over to your repo.

### CODE REVIEW

**Comment by fisidi** [comment]
@kmfoley what is your proposed strategy here? Do I merge the changes made by David then rework the changes? Or are there any other suggestions?

Just some backstory to remind you of our decision points:

Traditionally there was only 1 way to build WRF-CMAQ: 

1. Download/Clone WRF Repo
2. Download/Cone CMAQ Repo
3. Build CCTM code directory using bldscript (with #twoway option activated)
4. Move CCTM code directory to WRF repo and rename it to cmaq
5. Set appropriate WRF options (through environmental variables)
6. configure WRF
7. Clone/Download "two-way" tarball and run script within it to "assemble" WRF-CMAQ 
8. compile WRF

David's PR to the WRF repo eliminated step 7 (all the assembly code linking the two code bases are now in WRF). 

The v5.3.3 streamlined (our revisions -- yours/mine/ben's) approach tried to condense steps (1,4,6,8) and put it in the bldscript to be done automatically via step 3. So the updated approached looks like:

1. Download/Cone CMAQ Repo
2. Set appropriate WRF options (through environmental variables)
3. Build CCTM code directory using bldscript (with #twoway option activated)

Previously our tutorial tried to capture both methods. David prefers the "traditional" method being the architect of that method"; while myself and the rest of the team probably likes option 2 because it piggy backs on building CMAQ ("if you can build CMAQ, you can build WRF-CMAQ"). 

Do we want to keep both methods or condense down to one?

**Comment by fisidi** [comment]
@kmfoley what is your proposed strategy here? Do I merge the changes made by David then rework the changes? Or are there any other suggestions?

Just some backstory to remind you of our decision points:

Traditionally there was only 1 way to build WRF-CMAQ: 

1. Download/Clone WRF Repo
2. Download/Cone CMAQ Repo
3. Build CCTM code directory using bldscript (with #twoway option activated)
4. Move CCTM code directory to WRF repo and rename it to cmaq
5. Set appropriate WRF options (through environmental variables)
6. configure WRF
7. Clone/Download "two-way" tarball and run script within it to "assemble" WRF-CMAQ 
8. compile WRF

David's PR to the WRF repo eliminated step 7 (all the assembly code linking the two code bases are now in WRF). 

The v5.3.3 streamlined (our revisions -- yours/mine/ben's) approach tried to condense steps (1,4,6,8) and put it in the bldscript to be done automatically via step 3. So the updated approached looks like:

1. Download/Cone CMAQ Repo
2. Build CCTM code directory using bldscript (with #twoway option activated)
3. Set appropriate WRF options (through environmental variables)

Previously our tutorial tried to capture both methods. David prefers the "traditional" method being the architect of that method"; while myself and the rest of the team probably likes option 2 because it piggy backs on building CMAQ ("if you can build CMAQ, you can build WRF-CMAQ"). 

Do we want to keep both methods or condense down to one?

**Comment by kmfoley** [comment]
Thank you for breaking it into those steps.  I would say just close this PR because I think I mangled the new process when trying to combine the steps form each one.  My goal was just to have the new streamlined process in the tutorial.  I might not be able to help much with this but we can talk tomorrow.

**Comment by fisidi** [comment]
@kmfoley, ok! I'll close the PR -- if we decide otherwise we can re-open the PR again.

**Pull request closed without merging**
